# Generated by Django 2.1.15 on 2024-07-21 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_date', models.DateField()),
                ('hospital', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relation', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Self', 'Self'), ('Other', 'Other')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_paid', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('dependents', models.ManyToManyField(related_name='policies', to='insurance.Dependent')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(choices=[('Individual', 'Health Individual'), ('Family', 'Health Family'), ('Senior', 'Health Senior Citizens')], default='Individual', max_length=20)),
                ('sum_assurance', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyPremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_type', models.CharField(choices=[('Gold', 'Gold'), ('Diamond', 'Diamond'), ('Platinum', 'Platinum')], default='Gold', max_length=20)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tier', models.PositiveIntegerField()),
                ('number_of_hospitals', models.PositiveIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='insurance.Policy')),
            ],
        ),
        migrations.AddField(
            model_name='healthpolicy',
            name='policy_premium',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='insurance.PolicyPremium'),
        ),
        migrations.AddField(
            model_name='healthpolicy',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='health_policy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='dependent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.Dependent'),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.HealthPolicy'),
        ),
    ]
