# Generated by Django 2.2 on 2024-07-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='s3_document_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
