# Generated by Django 2.2 on 2024-07-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_s3_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='s3_document_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
